// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _api_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on UserEvent with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UserEvent) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	if v, ok := interface{}(m.GetUserCreate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserEventValidationError{
				field:  "UserCreate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUserDelete()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserEventValidationError{
				field:  "UserDelete",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UserEventValidationError is the validation error returned by
// UserEvent.Validate if the designated constraints aren't met.
type UserEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserEventValidationError) ErrorName() string { return "UserEventValidationError" }

// Error satisfies the builtin error interface
func (e UserEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserEventValidationError{}

// Validate checks the field values on UserCreate with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UserCreate) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Email

	return nil
}

// UserCreateValidationError is the validation error returned by
// UserCreate.Validate if the designated constraints aren't met.
type UserCreateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserCreateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserCreateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserCreateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserCreateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserCreateValidationError) ErrorName() string { return "UserCreateValidationError" }

// Error satisfies the builtin error interface
func (e UserCreateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserCreate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserCreateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserCreateValidationError{}

// Validate checks the field values on UserDelete with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UserDelete) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Date

	return nil
}

// UserDeleteValidationError is the validation error returned by
// UserDelete.Validate if the designated constraints aren't met.
type UserDeleteValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserDeleteValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserDeleteValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserDeleteValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserDeleteValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserDeleteValidationError) ErrorName() string { return "UserDeleteValidationError" }

// Error satisfies the builtin error interface
func (e UserDeleteValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserDelete.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserDeleteValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserDeleteValidationError{}
